/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cnbleu_serialport_SerialPort */

#ifndef _Included_org_cnbleu_serialport_SerialPort
#define _Included_org_cnbleu_serialport_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cnbleu_serialport_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;IIIII)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_org_cnbleu_serialport_SerialPort_open
        (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     org_cnbleu_serialport_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_cnbleu_serialport_SerialPort_close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
